import type { DictionaryEntry, LearningModule } from '../types';

export const dictionaryEntries: DictionaryEntry[] = [
  {
    id: 'alphabet-a-bisindo',
    word: 'A',
    category: 'alfabet',
    type: 'bisindo',
    description: 'Tangan dominan membentuk huruf A dengan kepalan lembut dan ibu jari di sisi telunjuk.',
    imageUrl: 'https://via.placeholder.com/300?text=A',
    videoUrl: '',
  },
  {
    id: 'alphabet-b-sibi',
    word: 'B',
    category: 'alfabet',
    type: 'sibi',
    description: 'Telapak tangan terbuka tegak dengan jari-jari rapat dan ibu jari menekuk ke depan telapak.',
    imageUrl: 'https://via.placeholder.com/300?text=B',
    videoUrl: '',
  },
  {
    id: 'alphabet-c-bisindo',
    word: 'C',
    category: 'alfabet',
    type: 'bisindo',
    description: 'Jari-jari dan ibu jari melengkung membentuk setengah lingkaran seperti huruf C.',
    imageUrl: 'https://via.placeholder.com/300?text=C',
    videoUrl: '',
  },
  {
    id: 'alphabet-d-sibi',
    word: 'D',
    category: 'alfabet',
    type: 'sibi',
    description: 'Telunjuk tegak lurus, jari lain bertemu ibu jari membentuk lingkaran kecil.',
    imageUrl: 'https://via.placeholder.com/300?text=D',
    videoUrl: '',
  },
  {
    id: 'alphabet-e-bisindo',
    word: 'E',
    category: 'alfabet',
    type: 'bisindo',
    description: 'Ujung semua jari ditekuk mendekati telapak, ibu jari sejajar di depan jari.',
    imageUrl: 'https://via.placeholder.com/300?text=E',
    videoUrl: '',
  },
  {
    id: 'alphabet-f-sibi',
    word: 'F',
    category: 'alfabet',
    type: 'sibi',
    description: 'Ibu jari dan telunjuk membentuk lingkaran, tiga jari lainnya tegak ke atas.',
    imageUrl: 'https://via.placeholder.com/300?text=F',
    videoUrl: '',
  },
  {
    id: 'number-1-bisindo',
    word: '1',
    category: 'angka',
    type: 'bisindo',
    description: 'Telunjuk tegak ke atas, jari lain menggenggam lembut ke telapak tangan.',
    imageUrl: 'https://via.placeholder.com/300?text=1',
    videoUrl: '',
  },
  {
    id: 'number-2-sibi',
    word: '2',
    category: 'angka',
    type: 'sibi',
    description: 'Telunjuk dan jari tengah terbuka membentuk huruf V, jari lain tertutup.',
    imageUrl: 'https://via.placeholder.com/300?text=2',
    videoUrl: '',
  },
  {
    id: 'number-3-bisindo',
    word: '3',
    category: 'angka',
    type: 'bisindo',
    description: 'Ibu jari, telunjuk, dan jari tengah terbuka; dua jari lain menutup ke telapak.',
    imageUrl: 'https://via.placeholder.com/300?text=3',
    videoUrl: '',
  },
  {
    id: 'number-4-sibi',
    word: '4',
    category: 'angka',
    type: 'sibi',
    description: 'Empat jari terbuka tegak rapat, ibu jari menekuk ke dalam telapak.',
    imageUrl: 'https://via.placeholder.com/300?text=4',
    videoUrl: '',
  },
  {
    id: 'number-5-bisindo',
    word: '5',
    category: 'angka',
    type: 'bisindo',
    description: 'Semua jari dan ibu jari terbuka lebar dengan telapak menghadap ke depan.',
    imageUrl: 'https://via.placeholder.com/300?text=5',
    videoUrl: '',
  },
  {
    id: 'word-halo-bisindo',
    word: 'Halo',
    category: 'kata_umum',
    type: 'bisindo',
    description: 'Tangan terbuka di dekat pelipis lalu digerakkan kecil ke luar sebagai sapaan ramah.',
    imageUrl: 'https://via.placeholder.com/300?text=Halo',
    videoUrl: '',
  },
  {
    id: 'word-terima-kasih-sibi',
    word: 'Terima Kasih',
    category: 'kata_umum',
    type: 'sibi',
    description: 'Ujung jari tangan dominan menyentuh dagu lalu bergerak ke depan dengan halus.',
    imageUrl: 'https://via.placeholder.com/300?text=Terima+Kasih',
    videoUrl: '',
  },
  {
    id: 'word-maaf-bisindo',
    word: 'Maaf',
    category: 'kata_umum',
    type: 'bisindo',
    description: 'Kedua telapak tangan dikepalkan lembut lalu digerakkan melingkar kecil di dada.',
    imageUrl: 'https://via.placeholder.com/300?text=Maaf',
    videoUrl: '',
  },
  {
    id: 'word-tolong-sibi',
    word: 'Tolong',
    category: 'kata_umum',
    type: 'sibi',
    description: 'Telapak tangan terbuka diletakkan di depan dada lalu didorong sedikit ke depan.',
    imageUrl: 'https://via.placeholder.com/300?text=Tolong',
    videoUrl: '',
  },
  {
    id: 'word-nama-bisindo',
    word: 'Nama',
    category: 'kata_umum',
    type: 'bisindo',
    description: 'Dua jari telunjuk dan tengah dari kedua tangan saling bersilangan dua kali.',
    imageUrl: 'https://via.placeholder.com/300?text=Nama',
    videoUrl: '',
  },
  {
    id: 'word-saya-sibi',
    word: 'Saya',
    category: 'kata_umum',
    type: 'sibi',
    description: 'Telunjuk tangan dominan menunjuk ringan ke arah dada sendiri.',
    imageUrl: 'https://via.placeholder.com/300?text=Saya',
    videoUrl: '',
  },
  {
    id: 'word-kamu-bisindo',
    word: 'Kamu',
    category: 'kata_umum',
    type: 'bisindo',
    description: 'Telunjuk diarahkan lembut ke lawan bicara sebagai penanda orang kedua.',
    imageUrl: 'https://via.placeholder.com/300?text=Kamu',
    videoUrl: '',
  },
  {
    id: 'word-makan-sibi',
    word: 'Makan',
    category: 'kata_umum',
    type: 'sibi',
    description: 'Ujung jari rapat menyentuh area mulut berulang satu kali seperti gerakan menyuap.',
    imageUrl: 'https://via.placeholder.com/300?text=Makan',
    videoUrl: '',
  },
  {
    id: 'word-minum-bisindo',
    word: 'Minum',
    category: 'kata_umum',
    type: 'bisindo',
    description: 'Tangan membentuk seolah memegang gelas lalu dimiringkan ke arah mulut.',
    imageUrl: 'https://via.placeholder.com/300?text=Minum',
    videoUrl: '',
  },
  {
    id: 'phrase-selamat-pagi-bisindo',
    word: 'Selamat Pagi',
    category: 'frasa',
    type: 'bisindo',
    description: 'Gabungan isyarat selamat dan pagi dengan gerakan terbuka dari dada lalu menunjukkan matahari terbit.',
    imageUrl: 'https://via.placeholder.com/300?text=Selamat+Pagi',
    videoUrl: '',
  },
  {
    id: 'phrase-apa-kabar-sibi',
    word: 'Apa Kabar',
    category: 'frasa',
    type: 'sibi',
    description: 'Tangan dominan membentuk isyarat tanya lalu diikuti gerakan kabar di depan dada.',
    imageUrl: 'https://via.placeholder.com/300?text=Apa+Kabar',
    videoUrl: '',
  },
  {
    id: 'phrase-sampai-jumpa-bisindo',
    word: 'Sampai Jumpa',
    category: 'frasa',
    type: 'bisindo',
    description: 'Kedua telunjuk diarahkan saling mendekat lalu bergerak menjauh sebagai penanda perpisahan.',
    imageUrl: 'https://via.placeholder.com/300?text=Sampai+Jumpa',
    videoUrl: '',
  },
  {
    id: 'phrase-selamat-malam-sibi',
    word: 'Selamat Malam',
    category: 'frasa',
    type: 'sibi',
    description: 'Isyarat selamat dilanjutkan gerakan telapak turun menutup seperti malam datang.',
    imageUrl: 'https://via.placeholder.com/300?text=Selamat+Malam',
    videoUrl: '',
  },
  {
    id: 'phrase-saya-mau-makan-bisindo',
    word: 'Saya Mau Makan',
    category: 'frasa',
    type: 'bisindo',
    description: 'Rangkaian isyarat saya, mau, lalu makan dengan jeda singkat yang jelas di setiap kata.',
    imageUrl: 'https://via.placeholder.com/300?text=Saya+Mau+Makan',
    videoUrl: '',
  },
];

export const learningModules: LearningModule[] = [
  {
    id: 'module-alfabet-isyarat',
    title: 'Alfabet Isyarat',
    description: 'Mengenal bentuk tangan untuk huruf dasar BISINDO dan SIBI dengan latihan bertahap.',
    level: 'pemula',
    duration: '5 menit',
    thumbnailUrl: 'https://via.placeholder.com/300?text=Alfabet+Isyarat',
    videoUrl: 'https://via.placeholder.com/300?text=Video+Alfabet',
    order: 1,
  },
  {
    id: 'module-angka-isyarat',
    title: 'Angka Isyarat',
    description: 'Belajar angka 1 sampai 10 untuk kebutuhan sehari-hari dan latihan kuis singkat.',
    level: 'pemula',
    duration: '6 menit',
    thumbnailUrl: 'https://via.placeholder.com/300?text=Angka+Isyarat',
    videoUrl: 'https://via.placeholder.com/300?text=Video+Angka',
    order: 2,
  },
  {
    id: 'module-salam-sapaan',
    title: 'Salam & Sapaan',
    description: 'Mempraktikkan sapaan umum seperti halo, selamat pagi, dan apa kabar.',
    level: 'pemula',
    duration: '7 menit',
    thumbnailUrl: 'https://via.placeholder.com/300?text=Salam+Sapaan',
    videoUrl: 'https://via.placeholder.com/300?text=Video+Salam',
    order: 3,
  },
  {
    id: 'module-percakapan-sehari-hari',
    title: 'Percakapan Sehari-hari',
    description: 'Menyusun kata menjadi dialog sederhana untuk sekolah, rumah, dan komunitas.',
    level: 'menengah',
    duration: '10 menit',
    thumbnailUrl: 'https://via.placeholder.com/300?text=Percakapan+Sehari-hari',
    videoUrl: 'https://via.placeholder.com/300?text=Video+Percakapan',
    order: 4,
  },
  {
    id: 'module-ekspresi-perasaan',
    title: 'Ekspresi Perasaan',
    description: 'Mempelajari isyarat untuk senang, sedih, marah, dan ekspresi emosional lainnya.',
    level: 'menengah',
    duration: '8 menit',
    thumbnailUrl: 'https://via.placeholder.com/300?text=Ekspresi+Perasaan',
    videoUrl: 'https://via.placeholder.com/300?text=Video+Perasaan',
    order: 5,
  },
  {
    id: 'module-kalimat-kompleks',
    title: 'Kalimat Kompleks',
    description: 'Menggabungkan beberapa ide dalam satu kalimat dengan struktur isyarat yang lebih panjang.',
    level: 'lanjutan',
    duration: '12 menit',
    thumbnailUrl: 'https://via.placeholder.com/300?text=Kalimat+Kompleks',
    videoUrl: 'https://via.placeholder.com/300?text=Video+Kompleks',
    order: 6,
  },
];

export const dailyWords: string[] = [
  'word-halo-bisindo',
  'word-terima-kasih-sibi',
  'word-maaf-bisindo',
  'word-tolong-sibi',
  'word-nama-bisindo',
  'word-saya-sibi',
  'phrase-apa-kabar-sibi',
];
